services:
  - type: web
    name: myclean-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

