services:
  - type: web
    name: myclean-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: myclean-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000

databases:
  - name: myclean-db
    databaseName: myclean
    user: myclean
    plan: free
